site_name: das

theme:
  name: "material"

use_directory_urls: false

plugins:
  - mkdocstrings

nav:
  - Homepage: index.md
  - Drivers:
      - drivers/avs.md
  - Module reference:
      - reference/common.md
      - reference/drivers.md
      - reference/print.md
